name: student-chek
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '20'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
          build-root-directory: app

      - run: ./app/gradlew build -p app
      - run: env

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java/
        with:
          coverageCommand: ./app/gradlew jacocoTestReport -p app
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
      - run: echo $CC_TEST_REPORTER_ID