name: student-chek
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '20'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
          build-root-directory: app

      - run: ./app/gradlew build -p app --no-daemon
#      - run: ./app/gradlew checkstyleMain -p app
#      - run: sudo ./app/gradlew test -p app

#name: student-check
#
#on:
#  - push
#  - pull_request
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '20'
#          distribution: 'temurin'
#      - uses: gradle/gradle-build-action@v2
#        with:
#          gradle-version: 8.5
#      - run: ./gradlew checkstyleMain
#      - run: ./gradlew test